In [2]:
import numpy as np

In [9]:
a = np.random.randint(3,8,(6,4))

In [10]:
a

array([[7, 5, 3, 7],
       [6, 3, 7, 7],
       [5, 7, 3, 7],
       [5, 4, 4, 6],
       [6, 7, 5, 5],
       [3, 6, 5, 5]])

In [11]:
b = np.random.randint(4,10,(6,1))
b

array([[4],
       [4],
       [6],
       [6],
       [7],
       [7]])

In [13]:
c = np.c_[a,b]

In [14]:
c

array([[7, 5, 3, 7, 4],
       [6, 3, 7, 7, 4],
       [5, 7, 3, 7, 6],
       [5, 4, 4, 6, 6],
       [6, 7, 5, 5, 7],
       [3, 6, 5, 5, 7]])